import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  sales,
  books,
  children,
  customers,
}: Readonly<{
  sales: React.ReactNode;
  books: React.ReactNode;
  children: React.ReactNode;
  customers: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-4 gap-4 p-4 bg-gray-50 min-h-dvh">
      {children}
      {customers}
      {books}
      {sales}
    </div>
  );
}
